executable = "/media/kdam/Data/UCL/code/Project2/Project2/temp/oob"
function = "oob"

[simulator]
name = "gdb"

[simulator.options]
CF = true
OF = true
STACK_M = false
gdb_path = "/usr/bin/gdb"

[variables]
x = "x"
b0 = "(int) buf[0]"
b9 = "(int) buf[9]"
