executable = "/media/kdam/Data/UCL/code/Project2/Project2/temp/main"
function = "main"

[simulator]
name = "gdb"

[simulator.options]
CF = true
OF = true
STACK_M = false
gdb_path = "/usr/bin/gdb"

[variables]
arcg = "argc"
